#!/bin/bash

# CPU Temp Initial
temp_val=$(cat /sys/class/thermal/thermal_zone0/temp)
temp=$(echo "scale=1; $temp_val / 1000" | bc)
# CPU Usage Initial
cpu_line=$(awk '/^cpu / {print $2,$3,$4,$5,$6,$7,$8,$9,$10,$11}' /proc/stat)
read user nice system idle iowait irq softirq steal guest guest_nice <<< $cpu_line
prev_total=$(($user + $nice + $system + $idle + $iowait + $irq + $softirq + $steal + $guest + $guest_nice))
prev_idletot=$(($idle + $iowait))
# Disk IO Initial
disk_line=$(awk '/mmcblk0 / {print $6, $10}' /proc/diskstats)
read prev_r_sectors prev_w_sectors <<< $disk_line

while true; do
  # CPU Temp
  temp_val=$(cat /sys/class/thermal/thermal_zone0/temp)
  temp=$(echo "scale=1; $temp_val / 1000" | bc)
  # CPU Usage
  cpu_line=$(awk '/^cpu / {print $2,$3,$4,$5,$6,$7,$8,$9,$10,$11}' /proc/stat)
  read user nice system idle iowait irq softirq steal guest guest_nice <<< $cpu_line
  total=$(($user + $nice + $system + $idle + $iowait + $irq + $softirq + $steal + $guest + $guest_nice))
  idletot=$(($idle + $iowait))
  delta_total=$(($total - $prev_total))
  delta_idle=$(($idletot - $prev_idletot))
  if [ $delta_total -gt 0 ]; then
    cpu_perc=$(echo "scale=1; 100 * ($delta_total - $delta_idle) / $delta_total" | bc)
  else
    cpu_perc=0.0
  fi
  # Format CPU percentage with leading zero if below 10
  cpu_perc=$(printf "%04.1f" "$cpu_perc")
  # RAM Usage
  mem_line=$(awk '/MemTotal/ {tot=$2} /MemAvailable/ {avail=$2} END {print tot, avail}' /proc/meminfo)
  read mem_total mem_avail <<< $mem_line
  used=$(($mem_total - $mem_avail))
  ram_perc=$(echo "scale=1; $used * 100 / $mem_total" | bc)
  # Format RAM percentage with leading zero if below 10
  ram_perc=$(printf "%04.1f" "$ram_perc")
  # Disk IO
  disk_line=$(awk '/mmcblk0 / {print $6, $10}' /proc/diskstats)
  read r_sectors w_sectors <<< $disk_line
  delta_r=$(($r_sectors - $prev_r_sectors))
  delta_w=$(($w_sectors - $prev_w_sectors))
  # READ: Convert to MB if over 999 KB, else KB, always 3 digits
  if [ $delta_r -gt 1998 ]; then
    read_val=$(echo "scale=0; $delta_r / 2048" | bc)
    read_unit="MB/s"
  else
    read_val=$(echo "scale=0; $delta_r / 2" | bc)
    read_unit="KB/s"
  fi
  # WRITE: Convert to MB if over 999 KB, else KB, always 3 digits
  if [ $delta_w -gt 1998 ]; then
    write_val=$(echo "scale=0; $delta_w / 2048" | bc)
    write_unit="MB/s"
  else
    write_val=$(echo "scale=0; $delta_w / 2" | bc)
    write_unit="KB/s"
  fi
  read_val=$(printf "%03d" $read_val)
  write_val=$(printf "%03d" $write_val)
  # Format output
  printf -v data "TMP:%.1fC|CPU:%s%%|RAM:%s%%|R:%s%s|W:%s%s" "$temp" "$cpu_perc" "$ram_perc" "$read_val" "$read_unit" "$write_val" "$write_unit"
  echo -ne "\033[s\033[1;1H\033[K$data\033[u"
  prev_total=$total
  prev_idletot=$idletot
  prev_r_sectors=$r_sectors
  prev_w_sectors=$w_sectors
  sleep 1
done
